services:
  db:
    image: postgres:16
    container_name: event_ticketing_db
    environment:
      - POSTGRES_DB=event_ticketing
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - "7834:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: